name: Generate Electron Binaries

on:
  workflow_dispatch:

jobs:
  generate:
    strategy:
      matrix:
        os:
        - macos-latest
        - windows-latest
        # - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Install dependencies
      run: |
        cd electron-bin
        npm ci

    - name: Generate macOS
      if: runner.os == 'macOS'
      run: |
        cd electron-bin
        node generate-macos.js
    - name: Upload macOS
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: electron-macos
        path: electron-bin/temp/macos/*.zip

    - name: Install wine
      if: runner.os == 'Linux'
      run: sudo apt install wine
    - name: Generate Windows
      if: runner.os == 'Windows' || runner.os == 'Linux'
      run: |
        cd electron-bin
        node generate-windows.js
    - name: Upload Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: electron-windows
        path: electron-bin/temp/windows/*.zip
    - name: Upload Windows Crossbuild
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: electron-windows-crossbuild
        path: electron-bin/temp/windows/*.zip
